spring:
  datasource:
    url: jdbc:postgresql://postgres-sql:5432/data_jpa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

